import sqlalchemy
import os
import dotenv
from faker import Faker
import numpy as np

def database_connection_url():
    dotenv.load_dotenv()
    DB_USER: str = os.environ.get("POSTGRES_USER")
    DB_PASSWD = os.environ.get("POSTGRES_PASSWORD")
    DB_SERVER: str = os.environ.get("POSTGRES_SERVER")
    DB_PORT: str = os.environ.get("POSTGRES_PORT")
    DB_NAME: str = os.environ.get("POSTGRES_DB")
    return f"postgresql+psycopg2://{DB_USER}:{DB_PASSWD}@{DB_SERVER}:{DB_PORT}/{DB_NAME}"

# Create a new DB engine based on our connection string
engine = sqlalchemy.create_engine(database_connection_url(), use_insertmanyvalues=True, pool_pre_ping=True)

with engine.begin() as conn:
    conn.execute(sqlalchemy.text("""
    DROP TABLE IF EXISTS public.employees;
    DROP TABLE IF EXISTS public.dept;
    DROP TABLE IF EXISTS public.history;

    create table
    public.dept(
        dept_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
        created_at timestamp with time zone not null default now(),
        dept_name TEXT NULL,
        base_pay FLOAT,
        dept_populus INT
        
    ) tablespace pg_default;


    create table 
    public.employees(
        id BIGINT generated by default as identity,
        hire_date timestamp with time zone not null default now(),
        name text null,
        skills text null,
        pay REAL,
        department text null,
        level integer
        
    ) tablespace pg_default;


    create table 
    public.history(
        ledger_id BIGINT generated by default as identity,
        created_at timestamp with time zone not null default now(),
        emp_name text null,
        days_employed bigint,
        day_wage float,
        in_dept text null,
        emp_id bigint
        
    ) tablespace pg_default;
    """))
    

num_users = 1000000
fake = Faker()

# create fake employee data
with engine.begin() as conn:
    print("creating fake data...")
    for i in range(num_users):
        if (i % 10 == 0):
            print(i)
        
        emp_id = fake.pyint()
        profile = fake.profile()
        departments = fake.sentence()
        skills = ", ".join(fake.words())
        base_pay = fake.pyfloat(positive = True, min_value= 30000, max_value= 150000)
        pay = fake.pyfloat(positive=True, min_value = base_pay, max_value = 180000)
        day_wage = base_pay / 260 #260 working days in a year
        dept_id = fake.pyint()
        dept_populus = fake.pyint()
        level = fake.pyint(min_value= -2, max_value = 12)
        days_employed = fake.pyint(min_value=1, max_value=10000)

        dept = conn.execute(sqlalchemy.text("INSERT INTO dept (dept_name, base_pay, dept_populus) VALUES (:dept_name, :base_pay, :dept_populus)"),
        {"dept_name": departments,"base_pay":base_pay,"dept_populus":dept_populus})

        employees = conn.execute(sqlalchemy.text("INSERT INTO employees ( name, skills, pay, department, level) VALUES ( :name, :skills, :pay, :department, :level)"),
        {"name":profile['name'],"skills":skills,"pay":pay,"department":departments,"level":level})
    
        history = conn.execute(sqlalchemy.text("INSERT INTO history (emp_name, days_employed, day_wage, in_dept, emp_id)  VALUES (:emp_name, :days_employed, :day_wage, :in_dept, :emp_id)"), 
        { "emp_name": profile['name'], "days_employed": days_employed, "day_wage": day_wage, "in_dept": departments, "emp_id": emp_id })