create table
    public.dept(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
        created_at timestamp with time zone not null default now(),
        dept_name TEXT NULL,
        dept_id INTEGER NOT NULL UNIQUE,
        base_pay FLOAT,
        dept_populus INT,
        CONSTRAINT dept_id_pkey PRIMARY KEY (id)
    ) tablespace pg_default;


create table 
    public.employees(
        id bigint generated by default as identity,
        created_at timestamp with time zone not null default now(),
        name text null,
        skills text null,
        pay REAL
        department text null
        level integer
        CONSTRAINT employees_id_pkey (id)
    ) tablespace pg_default;